#!/usr/bin/env bash
set -euo pipefail

repo_root=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)

pass() { printf 'PASS: %s\n' "$1"; }
fail() { printf 'FAIL: %s\n' "$1" >&2; exit 1; }

require_file() {
  local path=$1 label=$2
  [[ -f "${path}" ]] || fail "missing ${label}: ${path}"
  pass "${label} exists"
}

forbid_file() {
  local path=$1 label=$2
  [[ ! -e "${path}" ]] || fail "${label} unexpectedly present: ${path}"
  pass "${label} absent"
}

require_executable() {
  local path=$1 label=$2
  [[ -x "${path}" ]] || fail "missing executable ${label}: ${path}"
  pass "${label} is executable"
}

require_grep() {
  local pattern=$1 path=$2 label=$3
  grep -Eq -- "${pattern}" "${path}" || fail "${label} not found in ${path}"
  pass "${label} present"
}

forbid_grep() {
  local pattern=$1 path=$2 label=$3
  if grep -Eq -- "${pattern}" "${path}"; then
    fail "${label} unexpectedly present in ${path}"
  fi
  pass "${label} absent"
}

require_submodule() {
  local name=$1 label=$2 submodule_path
  submodule_path=$(git -C "${repo_root}" config -f .gitmodules --get "submodule.${name}.path") \
    || fail "${label} missing from .gitmodules"
  [[ -e "${repo_root}/${submodule_path}/.git" ]] || fail "${label} checkout missing at ${submodule_path}"
  pass "${label} registered at ${submodule_path} and checked out"
}

require_submodule qbox "QBox submodule"
require_submodule sources/buildroot "Buildroot source submodule"
require_submodule sources/linux "Linux source submodule"
require_submodule sources/qemu "libqemu/QEMU source submodule"

require_grep 'branch = 2026\.02\.1' "${repo_root}/.gitmodules" "Buildroot 2026.02.1 pin"
require_grep 'submodule\.sources/linux\.branch feature/qbox_dev' <(git config --file "${repo_root}/.gitmodules" --get-regexp 'submodule\.sources/linux\.branch') "Linux qbox_dev branch pin"
require_grep 'submodule\.sources/qemu\.branch feature/qbox_dev' <(git config --file "${repo_root}/.gitmodules" --get-regexp 'submodule\.sources/qemu\.branch') "QEMU qbox_dev branch pin"
require_grep 'submodule\.sources/buildroot\.shallow false' <(git config --file "${repo_root}/.gitmodules" --get-regexp 'submodule\.sources/buildroot\.shallow') "Buildroot full-history submodule setting"
require_grep 'submodule\.sources/linux\.shallow false' <(git config --file "${repo_root}/.gitmodules" --get-regexp 'submodule\.sources/linux\.shallow') "Linux full-history submodule setting"
require_grep 'submodule\.sources/qemu\.shallow false' <(git config --file "${repo_root}/.gitmodules" --get-regexp 'submodule\.sources/qemu\.shallow') "QEMU full-history submodule setting"

external="${repo_root}/configs/buildroot/external/apollo_qbox"
board="${external}/board/apollo/apollo-qbox"
defconfig="${external}/configs/apollo_qbox_defconfig"
linux_config="${repo_root}/configs/linux/linux.config"
linux_dts="${repo_root}/configs/linux/apollo_soc.dts"
require_file "${external}/external.desc" "BR2_EXTERNAL descriptor"
require_file "${external}/Config.in" "BR2_EXTERNAL Config.in"
require_file "${external}/external.mk" "BR2_EXTERNAL external.mk"
require_file "${defconfig}" "Apollo QBox Buildroot defconfig"
require_file "${linux_config}" "standalone Linux config fragment"
require_file "${board}/device_table.txt" "early device node table"
require_file "${linux_dts}" "Apollo QBox DTS template"
require_file "${board}/genimage.cfg" "future ext4 genimage config"
forbid_file "${board}/linux.config" "Linux config under Buildroot board"
forbid_file "${board}/apollo_soc.dts" "Linux DTS under Buildroot board"
require_executable "${board}/post-build.sh" "post-build hook"
require_executable "${board}/post-image.sh" "post-image hook"
require_executable "${repo_root}/scripts/build_qbox_buildroot_arm64.sh" "Buildroot rootfs build script"
require_executable "${repo_root}/scripts/build_qbox_linux_arm64.sh" "standalone Linux build script"
require_executable "${repo_root}/scripts/stage_buildroot_artifacts.sh" "artifact staging script"
require_executable "${repo_root}/scripts/check_qbox_hexagon_smmu_reference.sh" "QBox Hexagon SMMU reference preflight script"
require_executable "${repo_root}/scripts/run_iree_tiny_cnn_host_smoke.sh" "IREE tiny-CNN host smoke script"
require_executable "${repo_root}/scripts/stage_iree_tiny_cnn_guest_artifacts.sh" "IREE tiny-CNN guest artifact staging script"
require_executable "${repo_root}/scripts/build_apollo_hexagon_guest_tools.sh" "Apollo Hexagon guest tool build script"
require_executable "${repo_root}/scripts/run_iree_tiny_cnn_qbox_guest_smoke.sh" "IREE tiny-CNN QBox guest smoke script"
require_executable "${repo_root}/scripts/run_iree_tiny_cnn_hexagon_qbox_guest_smoke.sh" "IREE tiny-CNN Hexagon QBox guest smoke script"

require_grep '^BR2_aarch64=y$' "${defconfig}" "AArch64 target"
require_grep '^BR2_cortex_a710=y$' "${defconfig}" "Cortex-A710 target tuning"
require_grep '^BR2_TOOLCHAIN_BUILDROOT_CXX=y$' "${defconfig}" "Buildroot C++ toolchain support"
require_grep '^BR2_INSTALL_LIBSTDCPP=y$' "${defconfig}" "target libstdc++ runtime for IREE runner"
require_grep '^BR2_CCACHE=y$' "${defconfig}" "Buildroot ccache"
require_grep '^BR2_TARGET_ROOTFS_CPIO=y$' "${defconfig}" "CPIO initramfs"
require_grep 'BR2_ROOTFS_DEVICE_TABLE=.*device_table\.txt' "${defconfig}" "early device table configured"
require_grep 'BR2_ROOTFS_POST_IMAGE_SCRIPT_ARGS=.*\.\./\.\./\.\./linux/apollo_soc\.dts' "${defconfig}" "external Linux DTS configured"
require_grep '^BR2_PACKAGE_HOST_DTC=y$' "${defconfig}" "host dtc"
forbid_grep '^BR2_LINUX_KERNEL' "${defconfig}" "Buildroot kernel build options"
forbid_grep 'sources/linux|linux-v7\.0|QBOX_LINUX' "${repo_root}/scripts/build_qbox_buildroot_arm64.sh" "Linux coupling in Buildroot script"
require_grep 'linux_src=\$\{QBOX_LINUX_SRC:-"\$\{repo_root\}/sources/linux"\}' "${repo_root}/scripts/build_qbox_linux_arm64.sh" "Linux source submodule usage"
require_grep 'configs/linux/linux\.config' "${repo_root}/scripts/build_qbox_linux_arm64.sh" "Linux config fragment location"
require_grep 'toolchain_prefix=\$\{QBOX_LINUX_CROSS_COMPILE:-"\$\{buildroot_output\}/host/bin/aarch64-buildroot-linux-gnu-"\}' "${repo_root}/scripts/build_qbox_linux_arm64.sh" "Buildroot toolchain reuse"
require_grep 'linux_cross_compile="\$\{ccache_bin\} \$\{toolchain_prefix\}"' "${repo_root}/scripts/build_qbox_linux_arm64.sh" "Linux ccache launcher"
require_grep 'Image \\' "${repo_root}/scripts/build_qbox_linux_arm64.sh" "standalone Linux Image target"
require_grep 'linux_image=\$\{QBOX_LINUX_IMAGE:-"\$\{linux_output\}/arch/arm64/boot/Image"\}' "${repo_root}/scripts/stage_buildroot_artifacts.sh" "staging uses standalone Linux Image"
require_grep 'linux,initrd-start = <0x0 __INITRD_START__>' "${linux_dts}" "post-image initrd start placeholder"
require_grep 'compatible = "arm,cortex-a710"' "${linux_dts}" "A710 CPU compatible"
require_grep 'reserved-memory' "${linux_dts}" "future SRAM reservations"
require_grep 'compatible = "arm,smmu-v3"' "${linux_dts}" "ARM SMMUv3 node"
require_grep '#iommu-cells = <0x1>' "${linux_dts}" "SMMUv3 iommu cells"
require_grep 'compatible = "apollo,hexagon-ip"' "${linux_dts}" "Apollo Hexagon device node"
require_grep 'iommus = <&smmu 0x1>' "${linux_dts}" "Hexagon device behind SMMUv3"
require_grep 'apollo,dma-path = "smmu-translated"' "${linux_dts}" "Hexagon DMA path contract"
require_grep 'apollo,smmu-stream-id = <0x1>' "${linux_dts}" "Hexagon SMMU StreamID contract"
require_grep 'apollo,dma-iova-base = <0x00 0x10000000>' "${linux_dts}" "Hexagon DMA IOVA base contract"
require_grep 'apollo,dma-window-size = <0x00 0x00600000>' "${linux_dts}" "Hexagon DMA IOVA window contract"
require_grep 'memory-region-names = "firmware", "dma-test"' "${linux_dts}" "Hexagon firmware and DMA-test SRAM bindings"
require_grep '^CONFIG_ARM_SMMU_V3=y$' "${linux_config}" "Linux SMMUv3 driver"
require_grep '^CONFIG_MISC_DEVICES=y$' "${linux_config}" "Linux miscdevice support"
require_grep '^CONFIG_APOLLO_HEXAGON_TEST=y$' "${linux_config}" "Apollo Hexagon test driver"
require_file "${repo_root}/sources/linux/drivers/soc/apollo/Kconfig" "Apollo Linux SoC Kconfig"
require_file "${repo_root}/sources/linux/drivers/soc/apollo/apollo-hexagon-test.c" "Apollo Hexagon Linux driver"
require_file "${repo_root}/sources/linux/include/uapi/linux/apollo_hexagon.h" "Apollo Hexagon userspace ABI header"
require_grep 'struct apollo_hexagon_dma_stress_job' "${repo_root}/sources/linux/include/uapi/linux/apollo_hexagon.h" "Apollo Hexagon DMA stress UAPI"
require_grep 'firmware dma traffic ok' "${repo_root}/sources/linux/drivers/soc/apollo/apollo-hexagon-test.c" "Linux firmware-DMA traffic check"
require_grep 'dma path smmu-translated' "${repo_root}/sources/linux/drivers/soc/apollo/apollo-hexagon-test.c" "Linux DMA path ABI check"
require_grep 'DMA path mismatch' "${repo_root}/sources/linux/drivers/soc/apollo/apollo-hexagon-test.c" "Linux DMA path DT/HW mismatch guard"
require_grep 'APOLLO_HEXAGON_IOC_SUBMIT_CNN' "${repo_root}/sources/linux/drivers/soc/apollo/apollo-hexagon-test.c" "Linux Hexagon userspace submit ioctl"
require_grep 'APOLLO_HEXAGON_IOC_DMA_STRESS' "${repo_root}/sources/linux/drivers/soc/apollo/apollo-hexagon-test.c" "Linux Hexagon DMA stress ioctl"
require_grep 'dynamic SMMU SG map refreshed' "${repo_root}/sources/linux/drivers/soc/apollo/apollo-hexagon-test.c" "Linux Hexagon dynamic SMMU SG map"
require_grep 'SG DMA stress ok queue=%u fence=%u bytes=%u segments=%u' "${repo_root}/sources/linux/drivers/soc/apollo/apollo-hexagon-test.c" "Linux Hexagon SG DMA stress verification"
require_grep 'SMMUv3 page-table walker/ATS/PRI/fault queue ready' "${repo_root}/sources/linux/drivers/soc/apollo/apollo-hexagon-test.c" "Linux SMMUv3 functional feature probe"
require_grep 'SMMUv3 architectural descriptor probe ok' "${repo_root}/sources/linux/drivers/soc/apollo/apollo-hexagon-test.c" "Linux SMMUv3 descriptor-walk probe"
require_grep 'APOLLO_TBU_FEATURE_ARCH_4_LEVEL_WALK' "${repo_root}/sources/linux/drivers/soc/apollo/apollo-hexagon-test.c" "Linux SMMUv3 4-level walk feature probe"
require_grep 'APOLLO_TBU_FEATURE_STREAM_TABLE_WALK' "${repo_root}/sources/linux/drivers/soc/apollo/apollo-hexagon-test.c" "Linux SMMUv3 stream table walk feature probe"
require_grep 'APOLLO_TBU_FEATURE_CONTEXT_DESCRIPTOR_WALK' "${repo_root}/sources/linux/drivers/soc/apollo/apollo-hexagon-test.c" "Linux SMMUv3 context descriptor walk feature probe"
require_grep 'APOLLO_TBU_FEATURE_ARCH_FAULT_REPLAY' "${repo_root}/sources/linux/drivers/soc/apollo/apollo-hexagon-test.c" "Linux SMMUv3 fault replay feature probe"
require_grep 'SMMUv3 stream/context descriptor probe ok' "${repo_root}/sources/linux/drivers/soc/apollo/apollo-hexagon-test.c" "Linux SMMUv3 stream/context descriptor probe"
require_grep 'SMMUv3 negative fault replay ok' "${repo_root}/sources/linux/drivers/soc/apollo/apollo-hexagon-test.c" "Linux SMMUv3 negative fault replay probe"
require_grep 'APOLLO_HEXAGON_PTW_PAGES' "${repo_root}/sources/linux/drivers/soc/apollo/apollo-hexagon-test.c" "Linux SMMUv3 4-level table staging"
require_grep 'async fence signaled queue=%u fence=%u' "${repo_root}/sources/linux/drivers/soc/apollo/apollo-hexagon-test.c" "Linux async fence/IRQ verification"
require_grep 'misc_register' "${repo_root}/sources/linux/drivers/soc/apollo/apollo-hexagon-test.c" "Linux /dev/apollo-hexagon registration"
require_grep 'dynamic SMMU map refreshed' "${repo_root}/sources/linux/drivers/soc/apollo/apollo-hexagon-test.c" "Linux dynamic SMMU map refresh"
require_grep 'kernel_build": "external:sources/linux"' "${board}/post-image.sh" "post-image records external kernel ownership"
require_grep 'mount -t devtmpfs devtmpfs /dev' "${board}/post-build.sh" "post-build early devtmpfs mount entry"
require_grep 'QBOX_IREE_GUEST_ARTIFACTS_DIR' "${board}/post-build.sh" "post-build optional IREE guest artifact hook"
require_grep '/opt/qbox/iree/tiny-cnn' "${board}/post-build.sh" "post-build IREE tiny-CNN guest install path"
require_grep '/dev/ttyAMA0[[:space:]]+c[[:space:]]+660' "${board}/device_table.txt" "static ttyAMA0 fallback node"
require_grep 'iree-base-runtime' "${repo_root}/scripts/stage_iree_tiny_cnn_guest_artifacts.sh" "IREE AArch64 runtime wheel source"
require_grep 'bin/iree-run-module' "${repo_root}/scripts/stage_iree_tiny_cnn_guest_artifacts.sh" "IREE guest runner staging"
require_file "${board}/guest-tools/apollo_iree_hexagon_runner.c" "Apollo IREE Hexagon guest runner source"
require_file "${board}/guest-tools/apollo_iree_hexagon_hal.c" "Apollo IREE Hexagon HAL source"
require_file "${board}/guest-tools/apollo_iree_hexagon_hal.h" "Apollo IREE Hexagon HAL header"
require_file "${board}/guest-tools/apollo_iree_hexagon_plugin.c" "Apollo IREE Hexagon dynamic HAL plugin source"
require_file "${board}/guest-tools/apollo_iree_hexagon_plugin.h" "Apollo IREE Hexagon dynamic HAL plugin header"
require_file "${board}/guest-tools/apollo_iree_executable_plugin_abi.h" "IREE executable plugin ABI shim header"
require_file "${board}/guest-tools/apollo_hexagon_uapi_guest.h" "Apollo Hexagon guest UAPI mirror"
require_grep 'apollo-iree-hexagon-runner' "${repo_root}/scripts/stage_iree_tiny_cnn_guest_artifacts.sh" "Apollo IREE Hexagon runner staging"
require_grep 'libapollo_iree_hexagon_hal_plugin\.so' "${repo_root}/scripts/stage_iree_tiny_cnn_guest_artifacts.sh" "Apollo IREE Hexagon dynamic HAL plugin staging"
require_grep 'apollo_hexagon\.vmfb\.meta' "${repo_root}/scripts/stage_iree_tiny_cnn_guest_artifacts.sh" "Apollo IREE Hexagon VMFB metadata staging"
require_grep 'command_buffer=fixed' "${repo_root}/scripts/stage_iree_tiny_cnn_guest_artifacts.sh" "Apollo IREE Hexagon command-buffer metadata"
require_grep 'fence=async-irq-poll' "${repo_root}/scripts/stage_iree_tiny_cnn_guest_artifacts.sh" "Apollo IREE Hexagon fence metadata"
require_grep 'APOLLO_HEXAGON_IOC_SUBMIT_CNN' "${board}/guest-tools/apollo_hexagon_uapi_guest.h" "Apollo IREE Hexagon HAL submit ABI"
require_grep 'APOLLO_HEXAGON_IOC_DMA_STRESS' "${board}/guest-tools/apollo_hexagon_uapi_guest.h" "Apollo IREE Hexagon HAL DMA stress ABI"
require_grep 'apollo_hexagon_load_executable' "${board}/guest-tools/apollo_iree_hexagon_hal.c" "Apollo IREE Hexagon executable metadata loader"
require_grep 'apollo_hexagon_queue_submit_cnn' "${board}/guest-tools/apollo_iree_hexagon_hal.c" "Apollo IREE Hexagon queue submit path"
require_grep 'command buffer submitted' "${board}/guest-tools/apollo_iree_hexagon_runner.c" "Apollo IREE Hexagon command buffer completion"
require_grep '1x1x2x2xf32=\[\[\[54 63\]\[90 99\]\]\]' "${repo_root}/scripts/run_iree_tiny_cnn_qbox_guest_smoke.sh" "IREE guest output contract"
require_grep 'EXEC @tiny_cnn_graph \[apollo-hexagon\]' "${repo_root}/scripts/run_iree_tiny_cnn_hexagon_qbox_guest_smoke.sh" "IREE Hexagon guest output contract"
require_grep 'SG DMA stress ok queue=0' "${repo_root}/scripts/run_iree_tiny_cnn_hexagon_qbox_guest_smoke.sh" "IREE Hexagon SG DMA stress contract"
require_grep 'bytes=131072 segments=8' "${repo_root}/scripts/run_iree_tiny_cnn_hexagon_qbox_guest_smoke.sh" "IREE Hexagon >64KB DMA stress contract"

qbox_root="${repo_root}/sources/qbox"
platform="${qbox_root}/platforms/buildroot/conf_aarch64.lua"
hexagon_smmu_cmake="${qbox_root}/tests/qbox/cpu/hexagon/CMakeLists.txt"
hexagon_smmu_readme="${qbox_root}/tests/qbox/cpu/hexagon/HEXAGON_SMMU_README.md"
require_file "${platform}" "QBox Buildroot AArch64 platform"
require_file "${hexagon_smmu_cmake}" "QBox Hexagon SMMU reference CMake"
require_file "${hexagon_smmu_readme}" "QBox Hexagon SMMU reference README"
require_file "${qbox_root}/platforms/buildroot/fw/arm64_bootloader.lua" "Buildroot ARM64 bootloader stub"
require_file "${qbox_root}/platforms/buildroot/fw/Artifacts/.gitignore" "artifact directory gitignore"
require_grep 'ARM_NUM_CPUS = 4' "${platform}" "4 Cortex-A710 CPUs"
require_grep 'cpu_arm_cortexA710' "${platform}" "Apollo QBox Cortex-A710 module"
require_grep 'apollo_soc\.dtb' "${platform}" "Buildroot DTB artifact"
require_grep 'rootfs\.cpio' "${platform}" "Buildroot initramfs artifact"
require_grep 'math\.floor\(i / 2\) << 8' "${platform}" "2x2 cluster mp_affinity mapping"
require_grep 'moduletype = "keep_alive"' "${platform}" "QBox simulation keep-alive component"
require_grep 'moduletype = "arm_smmuv3"' "${platform}" "QBox SMMUv3 component"
require_grep 'moduletype = "apollo_smmu_tbu"' "${platform}" "QBox Apollo SMMU TBU data-plane component"
require_grep 'regs = \{address=APOLLO_HEXAGON_CTRL \+ 0x1000' "${platform}" "QBox Apollo SMMU TBU dynamic map register window"
require_grep 'moduletype = "qemu_cpu_hexagon"' "${platform}" "QBox Hexagon CPU component"

require_grep 'moduletype = "apollo_hexagon_dma"' "${platform}" "QBox Apollo Hexagon DMA component"
require_grep 'translated_dma = \{bind = "&hexagon_smmu_tbu_0\.upstream"\}' "${platform}" "QBox Apollo Hexagon translated DMA binding"
require_grep 'stream_id = APOLLO_HEXAGON_STREAM_ID' "${platform}" "QBox Apollo Hexagon DMA StreamID"
require_grep 'smmu_translated = true' "${platform}" "QBox Apollo Hexagon SMMU-translated DMA contract"
require_grep 'iova_base = APOLLO_HEXAGON_DMA_IOVA' "${platform}" "QBox Apollo Hexagon DMA IOVA base"
require_grep 'pa_base = APOLLO_SHARED_SRAM' "${platform}" "QBox Apollo Hexagon DMA translated PA base"
require_grep 'window_size = APOLLO_HEXAGON_DMA_WINDOW_SIZE' "${platform}" "QBox Apollo Hexagon DMA translated window"
require_grep 'REG_MAP_CTRL' "${qbox_root}/systemc-components/apollo_smmu_tbu/include/apollo_smmu_tbu.h" "QBox Apollo SMMU TBU map control register"
require_grep 'MAP_CTRL_REMOVE' "${qbox_root}/systemc-components/apollo_smmu_tbu/include/apollo_smmu_tbu.h" "QBox Apollo SMMU TBU unmap control"
require_grep 'MAP_CTRL_CLEAR' "${qbox_root}/systemc-components/apollo_smmu_tbu/include/apollo_smmu_tbu.h" "QBox Apollo SMMU TBU clear control"
require_grep 'translate_segment' "${qbox_root}/systemc-components/apollo_smmu_tbu/include/apollo_smmu_tbu.h" "QBox Apollo SMMU TBU multi-page split translation"
require_grep 'FEATURE_PAGE_TABLE_WALKER' "${qbox_root}/systemc-components/apollo_smmu_tbu/include/apollo_smmu_tbu.h" "QBox Apollo SMMU TBU page-table walker feature"
require_grep 'FEATURE_ATS_CACHE' "${qbox_root}/systemc-components/apollo_smmu_tbu/include/apollo_smmu_tbu.h" "QBox Apollo SMMU TBU ATS cache feature"
require_grep 'FEATURE_PRI_QUEUE' "${qbox_root}/systemc-components/apollo_smmu_tbu/include/apollo_smmu_tbu.h" "QBox Apollo SMMU TBU PRI feature"
require_grep 'FEATURE_FAULT_QUEUE' "${qbox_root}/systemc-components/apollo_smmu_tbu/include/apollo_smmu_tbu.h" "QBox Apollo SMMU TBU fault queue feature"
require_grep 'FEATURE_ARCH_DESCRIPTOR_WALK' "${qbox_root}/systemc-components/apollo_smmu_tbu/include/apollo_smmu_tbu.h" "QBox Apollo SMMU TBU architectural descriptor walk feature"
require_grep 'FEATURE_ARCH_4_LEVEL_WALK' "${qbox_root}/systemc-components/apollo_smmu_tbu/include/apollo_smmu_tbu.h" "QBox Apollo SMMU TBU architectural 4-level walk feature"
require_grep 'FEATURE_STREAM_TABLE_WALK' "${qbox_root}/systemc-components/apollo_smmu_tbu/include/apollo_smmu_tbu.h" "QBox Apollo SMMU TBU stream table walk feature"
require_grep 'FEATURE_CONTEXT_DESCRIPTOR_WALK' "${qbox_root}/systemc-components/apollo_smmu_tbu/include/apollo_smmu_tbu.h" "QBox Apollo SMMU TBU context descriptor walk feature"
require_grep 'FEATURE_ARCH_FAULT_REPLAY' "${qbox_root}/systemc-components/apollo_smmu_tbu/include/apollo_smmu_tbu.h" "QBox Apollo SMMU TBU architectural fault replay feature"
require_grep 'FEATURE_ARCH_ATS_PRI_PROTOCOL' "${qbox_root}/systemc-components/apollo_smmu_tbu/include/apollo_smmu_tbu.h" "QBox Apollo SMMU TBU architectural ATS/PRI protocol feature"
require_grep 'architectural stream table walk' "${qbox_root}/systemc-components/apollo_smmu_tbu/include/apollo_smmu_tbu.h" "QBox Apollo SMMU TBU stream-table-walk log"
require_grep 'architectural context descriptor walk' "${qbox_root}/systemc-components/apollo_smmu_tbu/include/apollo_smmu_tbu.h" "QBox Apollo SMMU TBU context-descriptor-walk log"
require_grep 'architectural table walk' "${qbox_root}/systemc-components/apollo_smmu_tbu/include/apollo_smmu_tbu.h" "QBox Apollo SMMU TBU table-walk log"
require_grep 'architectural descriptor walk' "${qbox_root}/systemc-components/apollo_smmu_tbu/include/apollo_smmu_tbu.h" "QBox Apollo SMMU TBU descriptor-walk log"
require_grep 'architected fault replay queued' "${qbox_root}/systemc-components/apollo_smmu_tbu/include/apollo_smmu_tbu.h" "QBox Apollo SMMU TBU fault replay log"
require_grep 'architected ATS translation response' "${qbox_root}/systemc-components/apollo_smmu_tbu/include/apollo_smmu_tbu.h" "QBox Apollo SMMU TBU architected ATS response log"
require_grep 'architected PRI response' "${qbox_root}/systemc-components/apollo_smmu_tbu/include/apollo_smmu_tbu.h" "QBox Apollo SMMU TBU architected PRI response log"
require_grep 'REG_JOB_CTRL' "${qbox_root}/systemc-components/apollo_hexagon_dma/include/apollo_hexagon_dma.h" "QBox Apollo Hexagon job control register"
require_grep 'MAX_DMA_LEN = 256 \* 1024' "${qbox_root}/systemc-components/apollo_hexagon_dma/include/apollo_hexagon_dma.h" "QBox Apollo Hexagon >64KB DMA length"
require_grep 'CAP_MULTI_QUEUE' "${qbox_root}/systemc-components/apollo_hexagon_dma/include/apollo_hexagon_dma.h" "QBox Apollo Hexagon multi-queue capability"
require_grep 'CAP_ASYNC_FENCE' "${qbox_root}/systemc-components/apollo_hexagon_dma/include/apollo_hexagon_dma.h" "QBox Apollo Hexagon async fence capability"
require_grep 'start_powered_off = false' "${platform}" "QBox Hexagon firmware boot enabled"
require_grep 'APOLLO_HEXAGON_BOOT_ALIAS' "${platform}" "QBox Hexagon boot alias"
require_grep 'aliases=\{\{address=APOLLO_HEXAGON_BOOT_ALIAS' "${platform}" "QBox Hexagon SRAM boot alias mapping"
require_grep 'apollo_hexagon_dma\.bin' "${platform}" "QBox Hexagon firmware loader entry"
require_grep 'job_loop' "${qbox_root}/platforms/buildroot/fw/hexagon_dma_smoke.s" "QBox Hexagon firmware job loop"
require_grep '0x42580000' "${qbox_root}/platforms/buildroot/fw/hexagon_dma_smoke.s" "QBox Hexagon firmware CNN output payload"
require_grep 'dma_copy_job' "${qbox_root}/platforms/buildroot/fw/hexagon_dma_smoke.s" "QBox Hexagon firmware DMA copy job"
require_grep '0x53474f4b' "${qbox_root}/platforms/buildroot/fw/hexagon_dma_smoke.s" "QBox Hexagon firmware SG DMA result"
require_grep 'apollo_hexagon_dma' "${repo_root}/scripts/build_qbox_buildroot_platform.sh" "QBox Apollo Hexagon DMA build target"
require_grep 'apollo_smmu_tbu' "${repo_root}/scripts/build_qbox_buildroot_platform.sh" "QBox Apollo SMMU TBU build target"
require_grep 'apollo_hexagon_dma\.so' "${repo_root}/scripts/run_qbox_buildroot_boot.sh" "QBox Apollo Hexagon DMA runtime module check"
require_grep 'apollo_smmu_tbu\.so' "${repo_root}/scripts/run_qbox_buildroot_boot.sh" "QBox Apollo SMMU TBU runtime module check"
require_grep 'build_qbox_hexagon_firmware\.sh' "${repo_root}/scripts/stage_buildroot_artifacts.sh" "Hexagon firmware staging hook"
require_grep 'moduletype = "hexagon_globalreg"' "${platform}" "QBox Hexagon global register component"
require_grep 'APOLLO_HEXAGON_SRAM' "${platform}" "QBox Hexagon SRAM mapping"
require_grep 'libqemu_src=\$\{QBOX_LIBQEMU_SRC:-"\$\{repo_root\}/sources/qemu"\}' "${repo_root}/scripts/build_qbox_buildroot_platform.sh" "QBox local libqemu source override"
require_grep 'libqemu_targets=\$\{QBOX_LIBQEMU_TARGETS:-"aarch64;hexagon"\}' "${repo_root}/scripts/build_qbox_buildroot_platform.sh" "QBox AArch64 and Hexagon libqemu targets"
require_grep 'CPM_libqemu_SOURCE="\$\{libqemu_src\}"' "${repo_root}/scripts/build_qbox_buildroot_platform.sh" "QBox CPM libqemu source override"
require_grep 'CMAKE_C_COMPILER_LAUNCHER="\$\{ccache_bin\}"' "${repo_root}/scripts/build_qbox_buildroot_platform.sh" "QBox C ccache launcher"
require_grep 'CMAKE_CXX_COMPILER_LAUNCHER="\$\{ccache_bin\}"' "${repo_root}/scripts/build_qbox_buildroot_platform.sh" "QBox CXX ccache launcher"
require_grep 'keep_alive' "${repo_root}/scripts/build_qbox_buildroot_platform.sh" "QBox keep_alive build target"
require_grep 'keep_alive\.so' "${repo_root}/scripts/run_qbox_buildroot_boot.sh" "QBox keep_alive runtime module check"
require_grep 'arm_smmuv3' "${repo_root}/scripts/build_qbox_buildroot_platform.sh" "QBox SMMUv3 build target"
require_grep 'qemu_cpu_hexagon' "${repo_root}/scripts/build_qbox_buildroot_platform.sh" "QBox Hexagon build target"
require_grep 'arm_smmuv3\.so' "${repo_root}/scripts/run_qbox_buildroot_boot.sh" "QBox SMMUv3 runtime module check"
require_grep 'qemu_cpu_hexagon\.so' "${repo_root}/scripts/run_qbox_buildroot_boot.sh" "QBox Hexagon runtime module check"
require_grep 'QBOX_BOOT_NETDEV_STR' "${platform}" "QBox Apollo netdev runtime override"
require_grep 'QBOX_BOOT_HOSTFWD' "${repo_root}/scripts/run_qbox_buildroot_boot.sh" "QBox boot hostfwd conflict policy"
require_grep 'CAP_DIRECT_TLM' "${qbox_root}/systemc-components/apollo_hexagon_dma/include/apollo_hexagon_dma.h" "QBox Apollo Hexagon DMA direct path capability"
require_grep 'CAP_SMMU_TRANSLATED' "${qbox_root}/systemc-components/apollo_hexagon_dma/include/apollo_hexagon_dma.h" "QBox Apollo Hexagon DMA future translated capability"
require_grep 'translated_dma' "${qbox_root}/systemc-components/apollo_hexagon_dma/include/apollo_hexagon_dma.h" "QBox Apollo Hexagon DMA translated path seam"
require_grep 'SC_ZERO_OR_MORE_BOUND' "${qbox_root}/systemc-components/apollo_hexagon_dma/include/apollo_hexagon_dma.h" "QBox Apollo Hexagon optional DMA sockets"
require_grep 'RESULT_TLM_ERROR' "${qbox_root}/systemc-components/apollo_hexagon_dma/include/apollo_hexagon_dma.h" "QBox Apollo direct-TLM error result"
require_grep 'return false' "${qbox_root}/systemc-components/apollo_hexagon_dma/include/apollo_hexagon_dma.h" "QBox Apollo direct-TLM failure propagation"
require_file "${qbox_root}/systemc-components/apollo_smmu_tbu/include/apollo_smmu_tbu.h" "QBox Apollo SMMU TBU component"
require_grep 'TLM_ADDRESS_ERROR_RESPONSE' "${qbox_root}/systemc-components/apollo_smmu_tbu/include/apollo_smmu_tbu.h" "QBox Apollo SMMU TBU fault response"
require_grep 'APOLLO_SMMU_TBU: stream-id=0x' "${qbox_root}/systemc-components/apollo_smmu_tbu/include/apollo_smmu_tbu.h" "QBox Apollo SMMU TBU translation log"
require_grep 'APOLLO_SMMU_TBU: translation fault' "${qbox_root}/systemc-components/apollo_smmu_tbu/include/apollo_smmu_tbu.h" "QBox Apollo SMMU TBU fault log"
require_grep 'HEXAGON_SMMU_MCPU "hexagonv68"' "${hexagon_smmu_cmake}" "QBox Hexagon SMMU v68 firmware target"
require_grep '-mcpu=\$\{HEXAGON_SMMU_MCPU\}' "${hexagon_smmu_cmake}" "QBox Hexagon SMMU CMake mcpu usage"
require_grep '-mcpu="\$\{mcpu\}"' "${repo_root}/scripts/check_qbox_hexagon_smmu_reference.sh" "QBox Hexagon SMMU preflight mcpu usage"
require_grep 'Hexagon v68 or later' "${hexagon_smmu_readme}" "QBox Hexagon SMMU v68 README note"

if git -C "${qbox_root}" ls-files --error-unmatch platforms/buildroot/fw/Artifacts/Image.bin >/dev/null 2>&1; then
  fail "generated Image.bin must not be tracked"
fi
pass "generated boot artifacts are not tracked in qbox"

printf '\nLane conclusion: Buildroot owns rootfs/DTB generation only; Linux Image comes from sources/linux, and libqemu comes from sources/qemu.\n'
